### ISSUE TITLE
generate_boundary generates boundary not correctly parsed by some implementations 

### ISSUE THREAD

**Issue by zyddnys** [mikedilger/mime-multipart#13]
Result of generate_boundary contains '=' and '/', which is not correctly handle by some multipart implementations.
I have a very simple fix, hopefully you can merge it soon.
https://github.com/zyddnys/mime-multipart/commit/fc18017579f1f6b082c00d1a592e35a4b3218f06

**Comment by mikedilger** [comment]
Thanks for pointing this out.

According to this https://www.oreilly.com/library/view/programming-internet-email/9780596802585/ch03s04.html
MIME boundaries should probably only use letters, numbers, and '+'.  Standard base64 encoding (as it currently uses) will also generate '/' which is apparently forbidden.  So the fix should be replacing '/' with anything (e.g. 'x') and not using the urlsafe variant.  If you make that change as a pull request I'll merge it.
