### ISSUE TITLE
Broken links to hyper documentation

### ISSUE THREAD

**Issue by FliegendeWurst** [mikedilger/mime-multipart#3]
For example, on https://mikedilger.github.io/mime-multipart/mime_multipart/enum.Node.html, you link to "http://hyper.rs/hyper/hyper/header/struct.Headers.html", which no longer exists. "http://hyper.rs/hyper/v0.9.12/hyper/header/struct.Headers.html" would work.

**Comment by mikedilger** [comment]
Thanks.  Cargo doc generates these links.  I'm not sure how to fix it without manually editing a lot of output from cargo doc.  Ideas?

**Comment by mikedilger** [comment]
Docs are nowadays on docs.rs.
